"""
Report generator — builds Markdown and JSON reports from scan results.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime

from app.models import Finding, ScanResult, Severity

logger = logging.getLogger(__name__)


def generate_markdown_report(result: ScanResult) -> str:
    """Generate a complete Markdown report from scan results."""
    lines: list[str] = []

    lines.append("# 🛡️ SecureDeploy Security Scan Report")
    lines.append("")
    lines.append(f"**Scan ID:** `{result.scan_id}`  ")
    lines.append(f"**Source:** {result.source_type.value} — `{result.source_value}`  ")
    lines.append(
        f"**Scanned:** {result.started_at.strftime('%Y-%m-%d %H:%M:%S UTC') if result.started_at else 'N/A'}  "
    )
    lines.append(
        f"**Completed:** {result.completed_at.strftime('%Y-%m-%d %H:%M:%S UTC') if result.completed_at else 'N/A'}  "
    )
    lines.append("")

    # Summary section
    if result.summary:
        s = result.summary
        lines.append("---")
        lines.append("")
        lines.append("## 📊 Summary")
        lines.append("")
        lines.append(f"**Total Findings:** {s.total_findings}")
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        lines.append(f"| 🔴 Critical | {s.critical} |")
        lines.append(f"| 🟠 High | {s.high} |")
        lines.append(f"| 🟡 Medium | {s.medium} |")
        lines.append(f"| 🔵 Low | {s.low} |")
        lines.append(f"| ⚪ Info | {s.info} |")
        lines.append("")

        if s.by_category:
            lines.append("**By Category:**")
            for cat, count in s.by_category.items():
                emoji = {"code_pattern": "🔍", "dependency": "📦", "secret": "🔑"}.get(
                    cat, "•"
                )
                lines.append(f"- {emoji} {cat.replace('_', ' ').title()}: {count}")
            lines.append("")

        if s.scanners_used:
            lines.append(f"**Scanners Used:** {', '.join(s.scanners_used)}")
            lines.append("")

        if s.top_files:
            lines.append("**Most Affected Files:**")
            for fp in s.top_files[:5]:
                lines.append(f"- `{fp}`")
            lines.append("")

    # AI Analysis section
    if result.ai_analysis:
        lines.append("---")
        lines.append("")
        lines.append("## 🤖 AI Analysis")
        lines.append("")
        lines.append(result.ai_analysis)
        lines.append("")

    # Critical issues first
    critical_findings = [f for f in result.findings if f.severity == Severity.CRITICAL]
    if critical_findings:
        lines.append("---")
        lines.append("")
        lines.append("## 🚨 Critical Issues")
        lines.append("")
        for f in critical_findings:
            lines.extend(_format_finding(f))

    # All findings
    lines.append("---")
    lines.append("")
    lines.append("## 📋 All Findings")
    lines.append("")

    if not result.findings:
        lines.append("✅ **No security issues found.** Great job!")
        lines.append("")
    else:
        # Group by category
        for category_label, category_val in [
            ("🔍 Code Patterns", "code_pattern"),
            ("📦 Dependencies", "dependency"),
            ("🔑 Secrets", "secret"),
        ]:
            cat_findings = [
                f for f in result.findings if f.category.value == category_val
            ]
            if cat_findings:
                lines.append(f"### {category_label}")
                lines.append("")
                for f in cat_findings:
                    lines.extend(_format_finding(f))

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(
        f"*Report generated by SecureDeploy on "
        f"{datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}*"
    )
    lines.append("")

    return "\n".join(lines)


def _format_finding(f: Finding) -> list[str]:
    """Format a single finding as Markdown."""
    sev_badge = {
        Severity.CRITICAL: "🔴 CRITICAL",
        Severity.HIGH: "🟠 HIGH",
        Severity.MEDIUM: "🟡 MEDIUM",
        Severity.LOW: "🔵 LOW",
        Severity.INFO: "⚪ INFO",
    }.get(f.severity, f.severity.value)

    lines: list[str] = []
    lines.append(f"#### [{f.id}] {f.title}")
    lines.append("")
    lines.append(f"**Severity:** {sev_badge} &nbsp; **Scanner:** {f.scanner}")
    if f.cwe:
        lines.append(f" &nbsp; **CWE:** {f.cwe}")
    lines.append("")
    lines.append(f"> {f.description}")
    lines.append("")

    if f.file_path:
        loc = f"`{f.file_path}`"
        if f.line_start:
            loc += f" (line {f.line_start}"
            if f.line_end and f.line_end != f.line_start:
                loc += f"-{f.line_end}"
            loc += ")"
        lines.append(f"**Location:** {loc}")
        lines.append("")

    if f.code_snippet:
        lines.append("```")
        # Truncate very long snippets
        snippet = f.code_snippet[:500]
        lines.append(snippet)
        lines.append("```")
        lines.append("")

    if f.fix_suggestion:
        lines.append(f"**💡 Fix:** {f.fix_suggestion}")
        lines.append("")

    if f.reference_urls:
        lines.append("**References:**")
        for url in f.reference_urls:
            lines.append(f"- {url}")
        lines.append("")

    lines.append("---")
    lines.append("")

    return lines


def generate_json_report(result: ScanResult) -> str:
    """Generate a JSON report from scan results."""
    data = result.model_dump(mode="json")

    # Redact any code_snippet for secret-category findings (extra safety)
    for f in data.get("findings", []):
        if f.get("category") == "secret" and f.get("code_snippet"):
            f["code_snippet"] = "[REDACTED]"

    return json.dumps(data, indent=2, default=str)
