-- Create scan_history table
CREATE TABLE IF NOT EXISTS scan_history (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    git_url TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    summary JSONB
);

-- Create scan_reports table
CREATE TABLE IF NOT EXISTS scan_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id UUID NOT NULL REFERENCES scan_history(id) ON DELETE CASCADE,
    findings JSONB NOT NULL DEFAULT '[]'::JSONB
);

-- Enable Row Level Security
ALTER TABLE scan_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE scan_reports ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies for scan_history
CREATE POLICY "Users can only select their own scan history"
    ON scan_history FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can only insert their own scan history"
    ON scan_history FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only update their own scan history"
    ON scan_history FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only delete their own scan history"
    ON scan_history FOR DELETE
    USING (auth.uid() = user_id);

-- Create RLS Policies for scan_reports
-- Since scan_reports doesn't have a direct user_id, we join against scan_history
CREATE POLICY "Users can only select their own scan reports"
    ON scan_reports FOR SELECT
    USING (EXISTS (
        SELECT 1 FROM scan_history 
        WHERE scan_history.id = scan_reports.scan_id 
        AND scan_history.user_id = auth.uid()
    ));

CREATE POLICY "Users can only insert their own scan reports"
    ON scan_reports FOR INSERT
    WITH CHECK (EXISTS (
        SELECT 1 FROM scan_history 
        WHERE scan_history.id = scan_reports.scan_id 
        AND scan_history.user_id = auth.uid()
    ));

CREATE POLICY "Users can only delete their own scan reports"
    ON scan_reports FOR DELETE
    USING (EXISTS (
        SELECT 1 FROM scan_history 
        WHERE scan_history.id = scan_reports.scan_id 
        AND scan_history.user_id = auth.uid()
    ));
